### PR TITLE
Add foldNames function

### PR DESCRIPTION
**Pull request by chrisdotcode**

### CODE REVIEW

**Comment by chrisdotcode** [comment]
Oh my. Forgot to update doc when renaming the function. I'll fix that.

**Comment by chrisdotcode** [comment]
Finished. Ready for merging, @garyb , @jdegoes .

**Comment by jdegoes** [comment]
@chrisdotcode Looks good, can you resolve conflicts?

**Comment by chrisdotcode** [comment]
Will do.

**Comment by cryogenian** [comment]
I don't quite get the purpose of this fold-func. The same result can be achieved using following
```purescript
peel <<< (maybe defaultValue (either (runDirName >>> handleDirName) (runFileName >>> handleFileName)))
```

**Comment by safareli** [comment]
Closing this pr as in #33 structure of Pathy was simplified and similar fold function was added.
@chrisdotcode thanks for the work anyways!

**Pull request closed without merging**
